### ISSUE TITLE
Unable to pull container image

### ISSUE THREAD

**Issue by instantdreams** [11notes/docker-radicale#5]
I have tried the following :
```
$ docker pull radicale
Using default tag: latest
Error response from daemon: pull access denied for radicale, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

$ docker pull 11notes/radicale
Using default tag: latest
Error response from daemon: manifest for 11notes/radicale:latest not found: manifest unknown: manifest unknown

$ docker pull ghcr.io/11notes/radicale
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/11notes/radicale/manifests/latest": denied

$ docker pull ghcr/11notes/radicale
Using default tag: latest
Error response from daemon: pull access denied for ghcr/11notes/radicale, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Which container registry has the image?

**Comment by instantdreams** [comment]
Turns out there is no `latest` image. Changed to use `3.1.8`.

Please consider adding a latest tag to your build process.

**Comment by 11notes** [comment]
I know most if not all images on docker hub have the :latest tag. My personal view is to never use that tag for the simple reason of version control. There could be breaking changes between 3.1.8 and 4.0 just like there were between 2.0 and 3.0. Introducing the :latest tag together with people auto updating their containers via watchtower and other tools would have broken their installations.

**Comment by instantdreams** [comment]
Very good points. There is often a reliance on Watchtower, and I do not like upgrading unless I've reviewed the release notes. That's why all my docker hosts run [Diun](https://crazymax.dev/diun/) instead of Watchtower.

I'll let you know if Diun notices an update next time you push a release.
