### ISSUE TITLE
Container is always unhealthy

### ISSUE THREAD

**Issue by instantdreams** [11notes/docker-radicale#6]
My container is always reporting a status of unhealthy. I checked the shell script:
```
$ docker exec -it radicale sh

/ $ ls -lha /usr/local/bin/
total 16K
drwxr-xr-x    1 root     root        4.0K Sep 13 05:31 .
drwxr-xr-x    1 root     root        4.0K Sep 13 05:31 ..
-rwxr-xr-x    1 root     root         348 Sep 13 05:31 entrypoint.sh
-rwxr-xr-x    1 root     root          66 Sep 13 05:31 healthcheck.sh

/ $ cat /usr/local/bin/healthcheck.sh
#!/bin/ash
  curl --max-time 5 -kILs --fail https://localhost:5232/

/ $ curl https://localhost:5232
curl: (35) OpenSSL/3.1.2: error:0A00010B:SSL routines::wrong version number

/ $ curl http://localhost:5232
Redirected to /.web/

```

The healthcheck.sh script should be changed to use http://localhost:5232/.

**Comment by 11notes** [comment]
Hi @instantdreams,
Thanks for the reply. The healtcheck in the container is checking HTTPS with the self signed certificate generated at start in entrypoint.sh. The healtcheck succeeds and the container show status (healthy) like it should with the default configuration. When you have a custom configuration, make sure you set certificate and key in [server] like this:

```
[server]
ssl = True
certificate = /my/custom/cert.pem
key = /my/custom/key.pem
```

Here is an example of a successfull run, just with the default configuration:
# docker run --name radicale -p 5232:5232 -d 11notes/radicale:3.1.8
# docker ps -a
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
3b74346270b6   11notes/radicale:3.1.8   "/usr/local/bin/entr…"   21 minutes ago   Up 21 minutes (healthy)   0.0.0.0:5232->5232/tcp, :::5232->5232/tcp   radicale

Does this solve your issue?

**Comment by 11notes** [comment]
This error comes from opening a HTTP connection to a HTTPS endpoint. You probably set http:// in traffic to the radicale instance instead of https://. The reason to use https behind the proxy instead of http is to secure the traffic even from within the network (zero trust policy). Here is the output of one of my instances. 

```
# access via HTTP instead of HTTPS
[2023-10-04 23:20:08 +0200] [1/Thread-1267 (process_request_thread)] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1006)

# access via HTTPS but directly on IP:port, no valid SSL (no proxy)
[2023-10-04 23:20:21 +0200] [1/Thread-1269 (process_request_thread)] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1006)
```
